#!/bin/bash
set -e

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo "Build Nessus-data image."
docker build $options -t sometheycallme/docker-nessus .

echo "Create Nessus-data image."
docker create -v /opt/nessus --name nessus-data sometheycallme/docker-nessus-data .

echo "Build Nessus image."
docker build $options -t sometheycallme/docker-nessus .

echo "Show image sizes."
docker images | egrep '^nessus\b' | sort

echo
echo "WARN: you should docker tag the docker-nessus image."
echo
