#!/bin/bash
set -e

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo
echo "Build Nessus image."
docker build $options -t sometheycallme/docker-nessus nessus-app/

echo
echo "Show image sizes."
docker images | grep -E '^sometheycallme/docker-nessus\b' | sort

echo
echo "WARN: you should docker tag the docker-nessus image."
echo
